const careers = [
  {
    id: "software-developer",
    name: "Software / Application Developer",
    category: "Building",
    accent: "BUILD",
    description:
      "Turn messy problems into products people can use. You will translate ideas into reliable, maintainable software.",
    dayToDay: [
      "Build and test features",
      "Debug applications and improve performance",
      "Collaborate with designers and analysts",
    ],
    tools: ["JavaScript", "Python", "Git", "APIs"],
    expectations: [
      "One programming language",
      "Data structures basics",
      "Git and debugging",
      "A small deployed project",
    ],
    competitive: [
      "A clear portfolio",
      "Curiosity and learning speed",
      "Readable code",
      "Team communication",
    ],
    salary: "Entry $72k / Mid $102k / Senior $137k",
    skills: ["problem solving", "coding", "creating", "independent"],
    matches: { build: 5, data: 1, protect: 1, solve: 2, design: 2, cloud: 3 },
  },
  {
    id: "data-analyst",
    name: "Data Analyst or Data Scientist",
    category: "Data",
    accent: "DATA",
    description:
      "Find the signal in the noise, then make it useful. Analysts connect evidence to decisions across a business.",
    dayToDay: [
      "Clean and explore datasets",
      "Build dashboards and recurring reports",
      "Present insights to stakeholders",
    ],
    tools: ["SQL", "Excel", "Tableau", "Python"],
    expectations: [
      "SQL joins and aggregations",
      "Basic statistics",
      "Data visualization",
      "Clear written analysis",
    ],
    competitive: [
      "A portfolio case study",
      "Business curiosity",
      "Strong presentation",
      "Comfort with ambiguity",
    ],
    salary: "Entry $60k / Mid $82k / Senior $108k",
    skills: ["patterns", "analyzing", "collaborative", "helping"],
    matches: { build: 1, data: 5, protect: 1, solve: 3, design: 1, cloud: 1 },
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "Protecting",
    accent: "SECURITY",
    description:
      "Keep systems trustworthy. You investigate signals, reduce risk, and help teams respond when the unexpected happens.",
    dayToDay: [
      "Monitor alerts and investigate incidents",
      "Review access, logs, and vulnerabilities",
      "Document findings and recommend controls",
    ],
    tools: ["Wireshark", "SIEM", "Linux", "Python"],
    expectations: [
      "Networking fundamentals",
      "Authentication concepts",
      "Log analysis",
      "Security mindset",
    ],
    competitive: [
      "Hands-on labs",
      "Security certifications",
      "Calm investigation",
      "Precise documentation",
    ],
    salary: "Entry $68k / Mid $96k / Senior $130k",
    skills: ["puzzles", "protecting", "independent", "patterns"],
    matches: { build: 1, data: 2, protect: 5, solve: 2, design: 0, cloud: 2 },
  },
  {
    id: "business-systems-analyst",
    name: "Business / Systems Analyst",
    category: "Solving",
    accent: "SYSTEMS",
    description:
      "Make work make more sense. Analysts bridge people, process, and technology to turn needs into workable systems.",
    dayToDay: [
      "Interview stakeholders and map processes",
      "Write requirements and acceptance criteria",
      "Coordinate testing and implementation",
    ],
    tools: ["SQL", "Jira", "BPMN", "Excel"],
    expectations: [
      "Requirements gathering",
      "Process modeling",
      "Clear documentation",
      "Facilitation basics",
    ],
    competitive: [
      "Empathy for users",
      "A process portfolio",
      "Structured thinking",
      "Confident communication",
    ],
    salary: "Entry $64k / Mid $88k / Senior $115k",
    skills: ["people", "solving", "collaborative", "leading"],
    matches: { build: 2, data: 2, protect: 1, solve: 5, design: 2, cloud: 1 },
  },
  {
    id: "it-project-manager",
    name: "IT Project Manager",
    category: "Leading",
    accent: "LEAD",
    description:
      "Move complex technology work from idea to impact. Project managers create clarity, momentum, and shared ownership across a team.",
    dayToDay: [
      "Plan milestones, scope, and dependencies",
      "Run standups and communicate project health",
      "Manage risks, decisions, and stakeholder expectations",
    ],
    tools: ["Jira", "Excel", "Teams", "Roadmaps"],
    expectations: [
      "Basic project planning",
      "Clear status communication",
      "Risk and issue tracking",
      "Comfort with agile concepts",
    ],
    competitive: [
      "A project leadership example",
      "Reliable follow-through",
      "Calm prioritization",
      "Strong facilitation",
    ],
    salary: "Entry $67k / Mid $94k / Senior $128k",
    skills: ["leading", "organizing", "collaborative", "solving"],
    matches: { build: 2, data: 1, protect: 1, solve: 4, design: 2, cloud: 1 },
  },
  {
    id: "ux-product-manager",
    name: "UX Designer / Product Manager",
    category: "Designing",
    accent: "DESIGN",
    description:
      "Turn user needs into products people want to use. This path blends research, design, prioritization, and product judgment.",
    dayToDay: [
      "Research user needs and test assumptions",
      "Sketch, prototype, and refine experiences",
      "Prioritize product work with a cross-functional team",
    ],
    tools: ["Figma", "Miro", "Jira", "Analytics"],
    expectations: [
      "User research basics",
      "Wireframing and prototyping",
      "Prioritization frameworks",
      "Comfort presenting decisions",
    ],
    competitive: [
      "A thoughtful case study",
      "Empathy for users",
      "Clear design rationale",
      "Product curiosity",
    ],
    salary: "Entry $62k / Mid $91k / Senior $125k",
    skills: ["creating", "people", "designing", "collaborative"],
    matches: { build: 3, data: 1, protect: 0, solve: 3, design: 5, cloud: 0 },
  },
  {
    id: "erp-systems-consultant",
    name: "ERP / Systems Consultant",
    category: "Transforming",
    accent: "SYSTEMS",
    description:
      "Help organizations reshape how work gets done through enterprise systems such as SAP or Salesforce.",
    dayToDay: [
      "Learn a client's process and system landscape",
      "Configure, test, and document solutions",
      "Train users and guide implementation change",
    ],
    tools: ["SAP", "Salesforce", "SQL", "Excel"],
    expectations: [
      "Business process fundamentals",
      "Requirements documentation",
      "Systems thinking",
      "Comfort learning platforms",
    ],
    competitive: [
      "A process improvement example",
      "Client empathy",
      "Structured problem solving",
      "Adaptability across industries",
    ],
    salary: "Entry $66k / Mid $93k / Senior $126k",
    skills: ["solving", "people", "systems", "collaborative"],
    matches: { build: 2, data: 2, protect: 1, solve: 4, design: 2, cloud: 2 },
  },
  {
    id: "cloud-infrastructure-engineer",
    name: "Cloud / Infrastructure Engineer",
    category: "Scaling",
    accent: "CLOUD",
    description:
      "Build the dependable systems beneath modern products. Infrastructure engineers make software available, secure, and resilient.",
    dayToDay: [
      "Automate deployments and infrastructure",
      "Monitor reliability, performance, and cost",
      "Design systems for scale and recovery",
    ],
    tools: ["AWS", "Azure", "Linux", "Terraform"],
    expectations: [
      "Networking and operating systems",
      "Cloud service fundamentals",
      "Scripting and automation",
      "Monitoring and incident basics",
    ],
    competitive: [
      "A hands-on cloud project",
      "Infrastructure as code",
      "Reliability mindset",
      "Strong troubleshooting",
    ],
    salary: "Entry $74k / Mid $108k / Senior $145k",
    skills: ["cloud", "building", "puzzles", "independent"],
    matches: { build: 4, data: 1, protect: 3, solve: 2, design: 0, cloud: 5 },
  },
];
const careerOrder = [
  "software-developer",
  "business-systems-analyst",
  "data-analyst",
  "cybersecurity-analyst",
  "it-project-manager",
  "ux-product-manager",
  "erp-systems-consultant",
  "cloud-infrastructure-engineer",
];
careers.sort((a, b) => careerOrder.indexOf(a.id) - careerOrder.indexOf(b.id));
const quizQuestions = [
  {
    prompt: "What kind of problem makes you lose track of time?",
    options: [
      ["Building something from scratch", "build"],
      ["Finding a pattern nobody noticed", "data"],
      ["Tracking down what went wrong", "protect"],
      ["Making a messy process work", "solve"],
    ],
  },
  {
    prompt: "Your ideal workday has more...",
    options: [
      ["Code, prototypes, and creating", "build"],
      ["Charts, evidence, and analysis", "data"],
      ["Logs, puzzles, and investigation", "protect"],
      ["Conversations, maps, and decisions", "solve"],
    ],
  },
  {
    prompt: "How much coding sounds right?",
    options: [
      ["A lot", "build"],
      ["Some, alongside analysis", "data"],
      ["Some, alongside systems work", "protect"],
      ["Very little, if the problem is interesting", "solve"],
    ],
  },
  {
    prompt: "What do teammates count on you for?",
    options: [
      ["Making ideas real", "build"],
      ["Making information clear", "data"],
      ["Noticing the risk", "protect"],
      ["Getting people aligned", "solve"],
    ],
  },
  {
    prompt: "Which outcome feels most satisfying?",
    options: [
      ["A tool people actually use", "build"],
      ["A decision backed by evidence", "data"],
      ["A threat stopped early", "protect"],
      ["A better way of working", "solve"],
    ],
  },
];