const careers = [
  {
    id: "software-developer",
    name: "Software / Application Developer",
    category: "Building",
    accent: "BUILD",
    description:
      "Turn messy problems into products people can use. You will translate ideas into reliable, maintainable software.",
    dayToDay: [
      "Start with a morning standup meeting",
      "Review pull requests",
      "Write and test backend API routes or frontend UI components",
      "Debug edge-case defects in the staging pipeline",
    ],
    tools: [
      "TypeScript",
      "JavaScript",
      "C#",
      "Python",
      "React",
      "Angular",
      "Node.js",
      "REST/GraphQL",
      "SQL",
      "Git",
    ],
    expectations: [
      "One programming language",
      "Data structures basics",
      "Git and debugging",
      "A small deployed project",
    ],
    competitive: [
      "A clear portfolio",
      "Curiosity and learning speed",
      "Readable code",
      "Team communication",
    ],
    salary: "Entry $72k / Mid $102k / Senior $137k",
    skills: [
      "Full-stack development (TypeScript, JavaScript, C#, Python)",
      "Framework proficiency (React, Angular, Node.js)",
      "API design (REST/GraphQL)",
      "Relational database management",
      "Object-oriented design",
      "Version control (Git)",
    ],
    courses: [
      "IS 303 (Intro Programming)",
      "IS 403 (Principles of Business Programming)",
      "IS 402 (Database Systems)",
      "IS 413 (Enterprise Application Development)",
      "IS 537 (Data Structures)",
      "IS 542 (Web Development)",
      "IS 543 (Mobile Platform Development)",
    ],
    matches: { build: 5, data: 1, protect: 1, solve: 2, design: 2, cloud: 3 },
  },
  {
    id: "data-analyst",
    name: "Data Analyst or Data Scientist",
    category: "Data",
    accent: "DATA",
    description:
      "Find the signal in the noise, then make it useful. Analysts connect evidence to decisions across a business.",
    dayToDay: [
      "Extract and clean datasets from raw data warehouses using SQL",
      "Build predictive models or statistical charts to analyze customer churn",
      "Deliver insights to executives",
    ],
    tools: [
      "Python",
      "R",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "SQL",
      "Tableau",
      "Power BI",
    ],
    expectations: [
      "SQL joins and aggregations",
      "Basic statistics",
      "Data visualization",
      "Clear written analysis",
    ],
    competitive: [
      "A portfolio case study",
      "Business curiosity",
      "Strong presentation",
      "Comfort with ambiguity",
    ],
    salary: "Entry $60k / Mid $82k / Senior $108k",
    skills: [
      "Python/R data science stacks (Pandas, NumPy, Scikit-learn)",
      "Advanced SQL",
      "Predictive modeling",
      "Statistical analysis",
      "Dashboarding (Tableau, Power BI)",
      "Machine learning",
    ],
    courses: [
      "STAT 121 (Intro to Statistics)",
      "IS 455 (Predictive AI)",
      "IS 415 (Exploratory Data Analysis)",
      "IS 554 (Investigative Analytics)",
      "IS 555 (Data Science for Organizations)",
      "IS 556 (Data Engineering)",
    ],
    matches: { build: 1, data: 5, protect: 1, solve: 3, design: 1, cloud: 1 },
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "Protecting",
    accent: "SECURITY",
    description:
      "Keep systems trustworthy. You investigate signals, reduce risk, and help teams respond when the unexpected happens.",
    dayToDay: [
      "Monitor security dashboards for anomalous network traffic",
      "Investigate potential intrusion alerts",
      "Perform access log audits",
      "Write incident post-mortem reports to update internal security controls",
    ],
    tools: [
      "TCP/IP",
      "SIEM",
      "Threat modeling",
      "Vulnerability scanning",
      "Pen testing",
      "Incident response",
    ],
    expectations: [
      "Networking fundamentals",
      "Authentication concepts",
      "Log analysis",
      "Security mindset",
    ],
    competitive: [
      "Hands-on labs",
      "Security certifications",
      "Calm investigation",
      "Precise documentation",
    ],
    salary: "Entry $68k / Mid $96k / Senior $130k",
    skills: [
      "Network protocol analysis (TCP/IP)",
      "SIEM monitoring",
      "Threat modeling",
      "Vulnerability scanning",
      "Security compliance",
      "Penetration testing fundamentals",
      "Incident response",
    ],
    courses: [
      "IS 404 (IT Infrastructure)",
      "IS 414 (IS Security & Controls)",
      "IS 560 (Information Security Management)",
      "IS 565 (Digital Forensics)",
      "IS 567 (Cybersecurity & Pen Testing)",
    ],
    matches: { build: 1, data: 2, protect: 5, solve: 2, design: 0, cloud: 2 },
  },
  {
    id: "business-systems-analyst",
    name: "Business / Systems Analyst",
    category: "Solving",
    accent: "SYSTEMS",
    description:
      "Make work make more sense. Analysts bridge people, process, and technology to turn needs into workable systems.",
    dayToDay: [
      "Interview business users to map current operational workflows",
      "Translate business requests into developer-ready technical specifications",
      "Validate that newly delivered software features meet acceptance criteria",
    ],
    tools: [
      "Process mapping",
      "User stories",
      "SQL",
      "Wireframes",
      "Gap analysis",
      "BPMN",
    ],
    expectations: [
      "Requirements gathering",
      "Process modeling",
      "Clear documentation",
      "Facilitation basics",
    ],
    competitive: [
      "Empathy for users",
      "A process portfolio",
      "Structured thinking",
      "Confident communication",
    ],
    salary: "Entry $64k / Mid $88k / Senior $115k",
    skills: [
      "Process mapping",
      "User story mapping",
      "SQL",
      "Requirement gathering",
      "Wireframing",
      "Business communication",
      "Gap analysis",
      "Stakeholder facilitation",
    ],
    courses: [
      "IS 201 (Intro to IS)",
      "IS 401 (Project Management & Systems Design)",
      "IS 402 (Database Systems)",
      "M COM 320 (Management Communication)",
    ],
    matches: { build: 2, data: 2, protect: 1, solve: 5, design: 2, cloud: 1 },
  },
  {
    id: "it-project-manager",
    name: "IT Project Manager",
    category: "Leading",
    accent: "LEAD",
    description:
      "Move complex technology work from idea to impact. Project managers create clarity, momentum, and shared ownership across a team.",
    dayToDay: [
      "Host sprint planning and daily standups",
      "Unblock engineering bottlenecks",
      "Track project timelines against strict launch milestones",
      "Update business sponsors on project status",
    ],
    tools: [
      "Agile/Scrum",
      "Scope planning",
      "Risk assessment",
      "Schedule estimation",
      "Jira",
      "Asana",
    ],
    expectations: [
      "Basic project planning",
      "Clear status communication",
      "Risk and issue tracking",
      "Comfort with agile concepts",
    ],
    competitive: [
      "A project leadership example",
      "Reliable follow-through",
      "Calm prioritization",
      "Strong facilitation",
    ],
    salary: "Entry $67k / Mid $94k / Senior $128k",
    skills: [
      "Agile/Scrum methodologies",
      "Scope management",
      "Risk assessment",
      "Schedule estimation",
      "Resource allocation",
      "Cross-functional team leadership",
      "Project tools (Jira, Asana)",
    ],
    courses: [
      "IS 401 (Project Management & Systems Design)",
      "IS 562 (IS Project Management)",
      "HRM 391 (Organizational Effectiveness)",
      "IS 582 (Tech Strategy and Leadership)",
    ],
    matches: { build: 2, data: 1, protect: 1, solve: 4, design: 2, cloud: 1 },
  },
  {
    id: "ux-product-manager",
    name: "UX Designer / Product Manager",
    category: "Designing",
    accent: "DESIGN",
    description:
      "Turn user needs into products people want to use. This path blends research, design, prioritization, and product judgment.",
    dayToDay: [
      "Conduct usability interviews with prototype testers",
      "Synthesize feedback into wireframes",
      "Negotiate sprint backlog priority with engineering leads",
      "Define long-term product features",
    ],
    tools: [
      "User research",
      "Figma",
      "Product roadmaps",
      "Usability testing",
      "A/B testing",
      "Customer journeys",
    ],
    expectations: [
      "User research basics",
      "Wireframing and prototyping",
      "Prioritization frameworks",
      "Comfort presenting decisions",
    ],
    competitive: [
      "A thoughtful case study",
      "Empathy for users",
      "Clear design rationale",
      "Product curiosity",
    ],
    salary: "Entry $62k / Mid $91k / Senior $125k",
    skills: [
      "User research",
      "Wireframing/prototyping (Figma)",
      "Product roadmap prioritization",
      "Market research",
      "Usability testing",
      "A/B testing design",
      "Customer journey mapping",
    ],
    courses: [
      "IS 551 (User Experience Design)",
      "IS 401 (Project Management & Systems Design)",
      "MKTG 201 (Marketing Management)",
      "IS 581 (Managing a Software Startup)",
    ],
    matches: { build: 3, data: 1, protect: 0, solve: 3, design: 5, cloud: 0 },
  },
  {
    id: "erp-systems-consultant",
    name: "ERP / Systems Consultant (e.g., SAP, Salesforce)",
    category: "Transforming",
    accent: "SYSTEMS",
    description:
      "Help organizations reshape how work gets done through enterprise systems such as SAP or Salesforce.",
    dayToDay: [
      "Meet with corporate stakeholders to analyze core business operations (supply chain or CRM)",
      "Configure software settings to match business needs",
      "Train staff during platform rollouts",
    ],
    tools: [
      "SAP",
      "Salesforce",
      "Enterprise architecture",
      "Platform configuration",
      "Data migration",
      "Change management",
    ],
    expectations: [
      "Business process fundamentals",
      "Requirements documentation",
      "Systems thinking",
      "Comfort learning platforms",
    ],
    competitive: [
      "A process improvement example",
      "Client empathy",
      "Structured problem solving",
      "Adaptability across industries",
    ],
    salary: "Entry $66k / Mid $93k / Senior $126k",
    skills: [
      "Enterprise systems architecture",
      "Business process re-engineering",
      "Platform configuration",
      "Client management",
      "Data migration",
      "Enterprise change management",
    ],
    courses: [
      "IS 402 (Database Systems)",
      "IS 531 (Enterprise Infrastructure)",
      "IS 566 (Advanced Database Management)",
      "GSCM 201 (Global Supply Chain Management)",
    ],
    matches: { build: 2, data: 2, protect: 1, solve: 4, design: 2, cloud: 2 },
  },
  {
    id: "cloud-infrastructure-engineer",
    name: "Cloud / Infrastructure Engineer",
    category: "Scaling",
    accent: "CLOUD",
    description:
      "Build the dependable systems beneath modern products. Infrastructure engineers make software available, secure, and resilient.",
    dayToDay: [
      "Configure automated cloud deployment pipelines",
      "Monitor server health and cost metrics",
      "Write infrastructure scripts",
      "Resolve runtime uptime or routing issues",
    ],
    tools: [
      "AWS",
      "Azure",
      "GCP",
      "Terraform",
      "CloudFormation",
      "Docker",
      "Kubernetes",
      "Linux",
      "CI/CD",
    ],
    expectations: [
      "Networking and operating systems",
      "Cloud service fundamentals",
      "Scripting and automation",
      "Monitoring and incident basics",
    ],
    competitive: [
      "A hands-on cloud project",
      "Infrastructure as code",
      "Reliability mindset",
      "Strong troubleshooting",
    ],
    salary: "Entry $74k / Mid $108k / Senior $145k",
    skills: [
      "Cloud platforms (AWS, Azure, GCP)",
      "Infrastructure as Code (Terraform, CloudFormation)",
      "Containerization (Docker, Kubernetes)",
      "Linux system administration",
      "Networking routing/firewalls",
      "CI/CD pipelines",
    ],
    courses: [
      "IS 404 (IT Infrastructure)",
      "IS 531 (Enterprise Infrastructure)",
      "IS 590R (Network Administration)",
      "IS 556 (Data Engineering)",
    ],
    matches: { build: 4, data: 1, protect: 3, solve: 2, design: 0, cloud: 5 },
  },
];
const careerOrder = [
  "software-developer",
  "business-systems-analyst",
  "data-analyst",
  "cybersecurity-analyst",
  "it-project-manager",
  "ux-product-manager",
  "erp-systems-consultant",
  "cloud-infrastructure-engineer",
];
careers.sort((a, b) => careerOrder.indexOf(a.id) - careerOrder.indexOf(b.id));
const quizQuestions = [
  {
    prompt: "What kind of problem makes you lose track of time?",
    options: [
      ["Building something from scratch", "build"],
      ["Finding a pattern nobody noticed", "data"],
      ["Tracking down what went wrong", "protect"],
      ["Making a messy process work", "solve"],
    ],
  },
  {
    prompt: "Your ideal workday has more...",
    options: [
      ["Code, prototypes, and creating", "build"],
      ["Charts, evidence, and analysis", "data"],
      ["Logs, puzzles, and investigation", "protect"],
      ["Conversations, maps, and decisions", "solve"],
    ],
  },
  {
    prompt: "How much coding sounds right?",
    options: [
      ["A lot", "build"],
      ["Some, alongside analysis", "data"],
      ["Some, alongside systems work", "protect"],
      ["Very little, if the problem is interesting", "solve"],
    ],
  },
  {
    prompt: "What do teammates count on you for?",
    options: [
      ["Making ideas real", "build"],
      ["Making information clear", "data"],
      ["Noticing the risk", "protect"],
      ["Getting people aligned", "solve"],
    ],
  },
  {
    prompt: "Which outcome feels most satisfying?",
    options: [
      ["A tool people actually use", "build"],
      ["A decision backed by evidence", "data"],
      ["A threat stopped early", "protect"],
      ["A better way of working", "solve"],
    ],
  },
];
